<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
$this->doctype() 
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle(\Application\Module::TITLE)->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendName('node', substr($_SERVER['SERVER_ADDR'], 8) )
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->headLink(['rel' => 'apple-touch-icon', 'href' => $this->basePath() . '/img/apple-touch-icon.png'])
            ->prependStylesheet($this->basePath('css/style.css'), 'screen,print')
            ->prependStylesheet('https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css', 'screen,print')
        ?>
        

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile('https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js')
            ->prependFile('https://code.jquery.com/jquery-3.6.0.min.js')
            ->prependFile('https://kit.fontawesome.com/2b927546c5.js')
        ?>
    </head>
    <body>
    	<nav class="navbar navbar-expand-sm navbar-dark sticky-top" role="navigation">
        	<a class="navbar-brand" href="<?= $this->url('home') ?>">
        		<img src="<?= $this->basePath('img/cityseal.png') ?>" height="28" alt="Middletown, CT" />&nbsp;<?= \Application\Module::TITLE ?>
        	</a>
        	<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        		<span class="navbar-toggler-icon"></span>
        	</button>
        	<div class="collapse navbar-collapse" id="navbarNav">
        	<?= $this->navigation('Laminas\Navigation\Default')->menu()->setPartial('navigation'); ?>
    		</div>
		</nav>
        <div class="container mt-3">
        <!-- Flash Messenger -->
            <?php echo $this->partial('flashmessenger'); ?>
        	
            <?= $this->content ?>
            <hr>
            <footer id="footer">
                &copy; <?= date('Y') ?> by City of Middletown, Connecticut. All rights reserved. <?= sprintf('%s-%s',\Application\Module::VERSION,substr($_SERVER['SERVER_ADDR'], 8)) ?>
            </footer>
        </div>
        <?= $this->inlineScript() 

        ?>
    </body>
</html>